config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  # get 'home/index'
  get 'home/prices'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/crypto_compare.rb
require 'net/http'
require 'json'

class CryptoCompare
  attr_reader :api_url

  def initialize
    @api_url = 'https://min-api.cryptocompare.com/data'
  end

  def news
    url = "#{@api_url}/v2/news/?lang=EN"
    uri = URI(url)
    response = Net::HTTP.get uri

    JSON.parse response
  end

  def pricemultifull(fsyms, tsyms='USD')
    url = "#{@api_url}/pricemultifull?fsyms=#{fsyms}&tsyms=#{tsyms}"
    uri = URI(url)
    response = Net::HTTP.get uri

    JSON.parse response
  end

  def totalvolfull(limit=10, tsyms='USD')
    url = "#{@api_url}/top/totalvolfull?limit=#{limit}&tsym=#{tsyms}"
    uri = URI(url)
    response = Net::HTTP.get uri

    JSON.parse response
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # Grab News
    cc = CryptoCompare.new
    @news = cc.news

    # Grab Volume
    cc = CryptoCompare.new
    @volumes = cc.totalvolfull
  end

  def prices
    @symbol = params[:symbol].upcase unless params[:symbol].nil? || params[:symbol].empty?

    # Grab Price
    if @symbol
      cc = CryptoCompare.new
      @price = cc.pricemultifull(@symbol)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Crypto News Junkies', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Get Prices", home_prices_path, class: 'nav-link' %>
      </li>
    </ul>
    <%= form_tag home_prices_path, method: 'GET', class: 'form-inline my-2 my-lg-0' do %>
      <%= text_field_tag :symbol, nil, class: 'form-control mr-sm-2', placeholder: 'Lookup Crypto Symbol' %>
      <%= submit_tag 'Lookup', class: 'btn btn-outline-secondary my-2 my-sm-0' %>
    <% end %>
  </div>
</nav>

app/views/home/index.html.erb
<table class="table table-sm table-striped table-bordered table-hover">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Price</th>
      <th scope="col">24hr High</th>
      <th scope="col">24hr Low</th>
      <th scope="col">Market Cap</th>
    </tr>
  </thead>
  <tbody>
    <% @volumes['Data'].each do |index| %>
      <% index['DISPLAY'].each do |display, tsym| %>
      <tr>
        <td><%= image_tag "https://www.cryptocompare.com#{tsym['IMAGEURL']}", alt: tsym['FROMSYMBOL'], size: '24x24' %></td>
        <td><%= tsym['PRICE'] %></td>
        <td><%= tsym['HIGH24HOUR'] %></td>
        <td><%= tsym['LOW24HOUR'] %></td>
        <td><%= tsym['MKTCAP'] %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<div class="row">
    <% for news in @news['Data'] %>
    <div class="col-sm">
      <div class="card" style="width: 18rem;">
        <%= image_tag news['imageurl'], class: 'card-img-top', alt: news['source'] %>
        <div class="card-body">
          <h5 class="card-title"><%= news['title'] %></h5>
          <p class="card-text"><%= news['body'].html_safe %></p>
          <%= link_to 'Read More', news['url'], target: '_blank', class: 'btn btn-primary' %>
        </div>
      </div>
      <br />
    </div>
    <% end %>
</div>

app/views/home/prices.html.erb
<h1>Get price</h1>

<% if @symbol %>
  <% if @price['Response'] == 'Error' %>
    <div class="alert alert-warning" role="alert">
      <%= @price['Warning'] %>
    </div>
  <% else %>
    <div class="jumbotron">
      <h1 class="display-4">
        <%= image_tag "https://www.cryptocompare.com#{@price['DISPLAY'][@symbol]['USD']['IMAGEURL']}", alt: @price['DISPLAY'][@symbol]['USD']['FROMSYMBOL'], size: '64x64' %>
        <%= @symbol %>
      </h1>
      <p>
      Price: <%= @price['DISPLAY'][@symbol]['USD']['PRICE'] %><br>
      24hr High: <%= @price['DISPLAY'][@symbol]['USD']['HIGHDAY'] %><br>
      24hr Low: <%= @price['DISPLAY'][@symbol]['USD']['LOWDAY'] %><br>
      Market Cap: <%= @price['DISPLAY'][@symbol]['USD']['MKTCAP'] %><br></p>
    </div>
  <% end %>
<% else %>
  <h4 class="alert alert-warning">Please enter a symbol</h4>
<% end %>

<% @price %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoNews</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'home/navbar' %>
    <br />
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>